name: Mirror and run GitLab CI

on:
  push:
    branches:
      - master
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SocialGouv/gitlab-mirror-and-ci-action@v1
      with:
        args: "https://gitlab.fabrique.social.gouv.fr/SRE/infra-as-loop"
      env:
        GITLAB_HOSTNAME: "gitlab.fabrique.social.gouv.fr"
        GITLAB_USERNAME: "oauth2"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_PROJECT_ID: "209"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}